title: "8L09 Blog"
description: "Welcome to my blog!"
author: "Your Name"
theme: minima
url: "https://Mummanajagadeesh.github.io/8L09"
baseurl: "/8L09"
social_links:
  twitter: "https://twitter.com/yourhandle"
  github: "https://github.com/yourhandle"
  linkedin: "https://linkedin.com/in/yourhandle"
plugins:
  - jekyll-seo-tag
featured_posts:
  - 2024-11-01-welcome-to-blog
  - 2024-11-15-another-post
  - 2024-11-30-hello-world
