title: "8L09s by Jagadeesh"
description: "Welcome to my blog!!"
author: "Jagadeesh Mummana"
theme: minima
url: "https://Mummanajagadeesh.github.io/8L09"
baseurl: "/8L09"
social_links:
  github: "https://github.com/Mummanajagadeesh"
  linkedin: "https://www.linkedin.com/in/jagadeeeshmummana"
  instagram: "https://www.instagram.com/jagadeesh__97__"
plugins:
  - jekyll-seo-tag
featured_posts:
  - 2024-11-01-welcome-to-blog
  - 2024-11-15-another-post
  - 2024-11-30-hello-world
