title: "Technical Blog"
description: "Welcome to my blog!"
author: "Jagadeesh Mummana"
theme: minima
url: "https://Mummanajagadeesh.github.io/8L09"
baseurl: "/8L09"
social_links:
  twitter: "https://twitter.com/yourhandle"
  github: "https://github.com/Mummanajagadeesh"
  linkedin: "https://linkedin.com/in/yourhandle"
plugins:
  - jekyll-seo-tag
